project:
  type: book
  output-dir: docs

execute:
  echo: true           

book:
  title: "Comparing LIME vs SHAP: Model Interpretability Analysis on the Adult Dataset"
  author:
    - Puyuan Tian (pt2654)
  date: today
  repo-url: https://github.com/PuyuanTian37/5293FinalProject  
  repo-actions: [edit, issue]
  page-footer:
    right: |
      Built with <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - data.qmd
    - methods.qmd
    - results.qmd
    - visualization.qmd
    - discussion.qmd     

format:
  html:
    theme: cosmo
    code-fold: true
